env: prod

app:
  server:
    port: 8080
  
database:
  host: localhost
  port: 5433
  user: postgres
  password: secret
  dbname: getgoal
  sslmode: disable
  timezone: Asia/Bangkok

search:
  label_limit: 13
