app:
  server:
    port: 8080
  
search:
  label_limit: 13

database:
  host: localhost
  port: 5432
  user: postgres
  password: secret
  dbname: getgoal
  sslmode: false
  timezone: Asia/Bangkok

  secrets:
    jwt:
      accesskey: cp23ssa1
      refreshkey: refreshcp23ssa1